from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class PromptRequest(BaseModel):
    prompt: str

@app.get("/")
def home():
    return {"message": "LegalEase AI Backend Running"}

@app.post("/generate")
async def generate_doc(req: PromptRequest):
    p = req.prompt.lower()
    if "rent" in p or "2bhk" in p:
        doc = """RENTAL AGREEMENT - Chennai

Property: 2BHK, 11 Months
Rent: Rs.15000/month, Deposit: Rs.75000
Landlord: [Name], Tenant: [Name]

Terms:
1. Pay rent before 5th.
2. Maintain property.
3. Deposit refundable.
4. Electricity extra.

LANDLORD____ TENANT____"""
    else:
        doc = f"""LEGAL DOCUMENT for: {req.prompt}

This is AI generated legal draft as per Indian Law.
Jurisdiction: Chennai Court.

1. Parties, 2. Purpose, 3. Terms, 4. Rights,
5. Termination, 6. Signatures.

Full draft for: {req.prompt}

[Demo Mode - Works without API Key]
Generated by LegalEase AI"""
    return {"document": doc}

@app.post("/generate-document")
async def generate_doc2(req: PromptRequest):
    return await generate_doc(req)